version: "3.2"

services:
  minecraft:
    image: maikemota/vanilla-minecraft:${SERVER_VERSION}
    ports:
      - "${SERVER_PORT}:25565"
      - "${RCON_PORT}:25575"
    volumes:
      - ${WORLD_PATH}:/world
      - ${SERVER_PROPERTIES_PATH}:/minecraft/server.properties
    deploy:
      restart_policy:
        condition: "on-failure"
        delay: 10s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: "0.9"
          memory: "4096M"
        reservations:
          cpus: "0.3"
          memory: "512M"
