name: Docker Image CI
on:
  push:
    tags: '*'
jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      SOURCE_TAGE: ${{ steps.branch_name.outputs.SOURCE_TAG }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image}
      run: docker build . --tag maikemota/vanilla-minecraft:${SOURCE_TAG}
