name: Build and Publish
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Tag
        run: |
          echo "::set-env name=BRANCH_TAG::${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,'"
          echo "::set-output name=branch_tag::${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,'"
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maikemota/vanilla-minecraft:${{ env.BRANCH_TAG }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          build_args: SERVER_VERSION=${{ env.BRANCH_TAG }}
