name: Docker Image CI

on:
  push:
    tags: '*'
jobs:

  build:
    env:
      SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image}
      run: docker build . --tag maikemota/vanilla-minecraft:${SOURCE_TAG}
