name: Build and Publish
on:
  push:
    branches:    
    - main
    tags:
      - '*'

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Generate tag
        run: |
          $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') > TAG
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
          
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maikemota/vanilla-minecraft
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          build_args: SERVER_VERSION=$(cat TAG)
